### ISSUE TITLE
Need separate users for process flow commenting

### ISSUE THREAD

**Issue by KetchCyork** [KetchPartners/sapcommercialprojects#11]
For commenting on process flows and app screens can we turn off anonymous comments and require users to log in?

**Comment by weownthesky3** [comment]
I am not aware of a way to disallow anonymous commenting however anyone commenting who is not logged into their Axure share account can click on the name 'anonymous' and change it. Axure share is a free service so there is no reason why one shouldn't have an account to simply review/comment.
[https://share.axure.com/](url)
<img width="1200" alt="axurecomments" src="https://user-images.githubusercontent.com/29525920/36345785-95bda654-13ff-11e8-9b6b-56d9720d7cf5.png">

**Comment by KetchCyork** [comment]
OK will will have to ask users to note their name in each comment so we know who to feedback changes to
